const blessed = require('blessed');
const contrib = require('blessed-contrib');
const screen = blessed.screen({ smartCSR: true });
const parentBox = blessed.box({ parent: screen, top: 0, left: 0, width: 100, height: 30 });
parentBox.setContent("Sidebar text goes here\nIt is cool\n\n\n\n\nStats at bottom");
const map = contrib.map({ parent: parentBox, top: 1, left: 25, width: 70, height: 20, style: { shapeColor: 'cyan' } });
screen.render();
map.addMarker({ lat: 40, lon: -74, color: 'yellow', char: 'X' });
screen.render();
setTimeout(() => process.exit(0), 100);
